git:
  clone: false
dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
#  - "3.7-dev"  # 3.7 development branch
#  - "3.8-dev"  # 3.8 development branch
#  - "nightly"  # nightly build
# command to install dependencies
matrix:
  include:
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode10.2  # Python 3.7.2 running on macOS 10.14.3
      addons: 
        homebrew: 
          packages: 
          - git-lfs
          update: true
      language: shell       # 'language: python' is an error on Travis CI macOS

notifications:
  slack: $SLACK

install:
  - export GIT_HTTPS_MAX_REQUEST_BUFFER=10000M
  - git clone --depth=10 --branch=master --progress https://github.com/mehulagg/UnsplashImageFull.git mehulagg/UnsplashImageFull 
  - cd mehulagg/UnsplashImageFull
  - python3 -m pip install --upgrade pip
  - pip3 install -r requirements.txt
# command to run tests
script:
  - df -h
# scrapy crawl unsplash --nolog
# python3 download.py
  - git lfs install
  - git lfs track "*.jpg"
  - git config --global user.email "jonygupta80@gmail.com"
  - git config --global user.name "Mehul Aggarwal"
  - git add .
  - git commit -m '[skip ci] enable lfs'
  - git push https://mehulagg:$PAT_GITHUB_MEHULAGG@github.com/mehulagg/UnsplashImageFull.git HEAD:master
  - git push https://Wallpapers:$PAT_AZURE_JONYGUPTA80@dev.azure.com/Wallpapers/UnsplashImages/_git/UnsplashImageFull HEAD:master

