version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - run:
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
      - run:
          command: |
            mkdir ~/bin
            PATH=~/bin:$PATH
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            mkdir android
            cd android
            git config --global user.name "Jony"
            git config --global user.email "jonyg1355@gmail.com"
            repo init -u https://android.googlesource.com/platform/manifest --quiet
            repo sync --quiet
            git count-objects -v -H
