version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    steps:
      - run:
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
      - run:
          command: |
            mkdir ~/bin
            PATH=~/bin:$PATH
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
      - run:
          command: |
            PATH=~/bin:$PATH
            chmod a+x ~/bin/repo
            mkdir android
            cd android
            git config --global user.name "Jony"
            git config --global user.email "jonyg1355@gmail.com"
            repo init -u https://android.googlesource.com/platform/manifest --quiet
            repo sync --quiet
            du -sch
      - run:
          command: |
            cd android
            git init
            git config lfs.activitytimeout 0
            git config lfs.tlstimeout 120
            git config lfs.dialtimeout 120
            git config --global user.name "Mehul Aggarwal"
            git config --global user.email "jonyg1355@gmail.com"
            git lfs install
            git lfs track "*"
            git add *
            git commit -m "first commit"
            git remote add origin https://Preview1:ujiujf5fim7le36x7hv457hfysxxzz2dcmsh4r4pvicwwtd3vbra@dev.azure.com/Preview1/TestPreview/_git/android
            git push -u origin master
            
            
